name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Extract Version from pubspec.yaml
        id: pubspec
        run: |
          # Trích xuất version name (ví dụ: 1.1.0)
          VERSION_NAME=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          # Trích xuất build number gốc (ví dụ: 3000)
          VERSION_CODE=$(grep '^version: ' pubspec.yaml | cut -d '+' -f 2)
          
          # Tính toán build number mới: Lấy gốc cộng với run_number của GitHub
          NEW_BUILD_NUMBER=$((VERSION_CODE + github.run_number))
          
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "build_number=$NEW_BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "tag_name=v$VERSION_NAME+$NEW_BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Build APK (Split per ABI)
        run: |
          flutter build apk --release --split-per-abi \
            --target-platform android-arm,android-arm64 \
            --build-name=${{ steps.pubspec.outputs.version }} \
            --build-number=${{ steps.pubspec.outputs.build_number }} \
            --dart-define=GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Get Commits
        id: commits
        run: |
          COMMITS=$(git log -n 5 --pretty=format:"• %s")
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release and Upload APKs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.pubspec.outputs.tag_name }}
          name: Release ${{ steps.pubspec.outputs.tag_name }}
          body: ${{ steps.commits.outputs.changelog }}
          files: build/app/outputs/flutter-apk/*.apk
          generate_release_notes: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
